name = "kmh"
version = "1.0.0"
description = "Gleam implementation of Knuth’s multiplicative hashing."
licences = ["LGPL-2.1"]
repository = { type = "github", user = "mdarse", repo = "kmh" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
prime = ">= 0.1.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
